### ISSUE TITLE
enable turning off ad axios interception

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-browser#2]
![image](https://github.com/SpatialDays/stac-browser/assets/17437897/11e0b759-6102-4c4a-b52b-e32beb324247)

For some reason, VUE cant read env vars? Or I just don't know how to do it. The idea is to disable
axios intercept based on env var so it is not annoying when you are developing in the localhost.

That env var is set in the docker:

![image](https://github.com/SpatialDays/stac-browser/assets/17437897/12906c65-3fff-4caf-800e-5b7b0fee8b59)

**Comment by ivica3730k** [comment]
See https://github.com/SpatialDays/stac-browser/blob/2615d75ade67d49b36ddc63c856d1c43b30945ac/src/main.js

**Comment by james-hinton** [comment]
https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

**Comment by mountaincharlie** [comment]
Been trying a number of 'fixes' to get the process.env to work in main.js
Such as:
- adding this new plugin inside the vue.config.js
![image](https://github.com/SpatialDays/stac-browser/assets/85025426/20d3cd9c-c731-4e7f-b6a9-47384b8ef3d4)
- using import.meta.env. instead of process.env, but i believe this is actually only when Vite is being used which i think we aren't
- adding it this way in the vue.config.js
![image](https://github.com/SpatialDays/stac-browser/assets/85025426/dedf351f-76ba-40dc-9e46-6edb29d94b17)

There doesn't seem to be anything [here](https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code) which explains why the 'process' is not defined error occurs

Anything obvious im missing? Haven't really done much with Vue so its likely im misunderstanding something
